### ISSUE TITLE
Documentation of notebook versions

### ISSUE THREAD

**Issue by matbun** [Clearbloo/Feynman_GNN#1]
Hi!
May I ask you if you could explain which is the rationale behind the different notebook versions for `dataset_builder` and `Feynman_GNN` ? 

Can you confirm that if I want to replicate your results, I should just run `dataset_builder_v3_0.ipynb` and `Feynman_GNN_v5.0.ipynb`? I guess the other ones are older versions.

Thank you very much!

**Comment by Clearbloo** [comment]
Hi Matteo,

I apologize for the format. The version numbers are from before I
initialized a GitHub repository.

I plan to tidy this up in the future.

To replicate the results you can just run the dataset builder and the
network. It may require some set up of the directory. The current
arrangement is to process and store the Feynman diagrams in a Google drive
account mounted to Google Colab.

I hope this helps!

If you have any more questions please feel free to ask.

Kind regards,

Harrison

**Comment by matbun** [comment]
Hi Harrison!
The runtime environment is not a big problem. In [the fork I created](https://github.com/matbun/Feynman-GNN), I adapted the code to use the local filesystem and run in a conda environment.

My problem is that there are multiple versions both for the dataset builder and for the network. In my fork, I used `dataset_builder_v3_0.ipynb` to build the dataset, and `Feynman_GNN_v5.0.ipynb` to train the network. The network notebook has some problems and does not run as-is. I fixed them, but this makes me doubt about the goodness of Feynman_GNN_v5.0.ipynb` whatsoever. Probably it is an old version.

If you have an updated version of both notebooks, it would be nice to have them, also linked here is fine :)

**Comment by Clearbloo** [comment]
Hi Matteo,

Yes, sorry about that. I have just found a version 7 on my local computer.

I am quite busy at the moment. When I have some free time, I'd be happy to
try to reconcile the versions and update the github repository.

Kind regards

Harrison

**Comment by matbun** [comment]
Thank you very much!

**Comment by Clearbloo** [comment]
Just done some preliminary tidying. I will check that everything is running as expected and tidy some of the code too.

**Comment by Clearbloo** [comment]
I've now checked through and run a test. Seems to be working now, but some of the code still needs some tidying. Let me know if there is another issue.
